### ISSUE TITLE
Incompatible with Qwik?

### ISSUE THREAD

**Issue by TheAyes** [greensock/GSAP#596]
I'm trying to use this module with the [Qwik Framework](https://qwik.dev/) however upon trying to create an animation I receive this error:
<details>

```
09:12:56 [vite] Internal server error: Cannot read properties of undefined (reading 'querySelectorAll')
      at toArray (C:\Projekte\vault-of-ayes\node_modules\gsap\dist\gsap.js:640:175)
      at new Tween (C:\Projekte\vault-of-ayes\node_modules\gsap\dist\gsap.js:2967:130)
      at Object.to (C:\Projekte\vault-of-ayes\node_modules\gsap\dist\gsap.js:3357:14)
      at AsyncFunction.Toggle_component_useTask_zEtNv91157U [as resolved] (C:\Projekte\vault-of-ayes\modules\bismuth\src\components\toggle\toggle.component.tsx:15:22)
      at AsyncFunction.invokeApply (C:\Projekte\vault-of-ayes\node_modules\dist-dev\tsc-out\packages\qwik\dist-dev\tsc-out\packages\qwik\src\core\use\use-core.js:66:26)
      at AsyncFunction.invoke (C:\Projekte\vault-of-ayes\node_modules\dist-dev\tsc-out\packages\qwik\dist-dev\tsc-out\packages\qwik\src\core\use\use-core.js:58:24)
```

</details>

With a component like this:

<details>

```ts
import { component$, useSignal, useTask$ } from "@builder.io/qwik";
import { Toggle as HToggle } from "@qwik-ui/headless";
import { gsap } from "gsap";

import { styles } from ".";

export interface IToggle {
	defaultState: boolean;
}

export const Toggle = component$<IToggle>(({ defaultState = false, ...props }) => {
	let isPressed = useSignal(defaultState);

	useTask$(({ cleanup }) => {
		const tween = gsap.to(`.${styles.toggle}`, { x: 360, repeat: 100, ease: "power1.inOut" });

		cleanup(() => {
			tween.revert();
		});
	});

	return (
		<HToggle
			{...props}
			bind:pressed={isPressed}
			onPressedChange$={(p) => {}}
			onClick$={() => {}}
			class={[styles.toggle, "toggle"]}
		>
			<span></span>
		</HToggle>
	);
});
```

</details>

Previously I tried using the flip plugin which also didn't work out the way it's supposed to be:

<details>

```
09:36:22 [vite] Error when evaluating SSR module /src/components/toggle/toggle.component.tsx: failed to import "gsap/Flip"
|- C:\Projekte\vault-of-ayes\node_modules\gsap\Flip.js:12
import { getGlobalMatrix, _getDocScrollTop, _getDocScrollLeft, Matrix2D, _setDoc, _getCTM } from "./utils/matrix.js";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1357:20)
    at Module._compile (node:internal/modules/cjs/loader:1414:41)
    at Module._extensions..js (node:internal/modules/cjs/loader:1534:10)
    at Module.load (node:internal/modules/cjs/loader:1265:32)
    at Module._load (node:internal/modules/cjs/loader:1081:12)
    at cjsLoader (node:internal/modules/esm/translators:344:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:284:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:235:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:461:24)
    at async nodeImport (file:///C:/Projekte/vault-of-ayes/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:52735:15)

09:36:22 [vite] Error when evaluating SSR module /src/components/toggle/index.ts: failed to import "gsap/Flip"
|- C:\Projekte\vault-of-ayes\node_modules\gsap\Flip.js:12
import { getGlobalMatrix, _getDocScrollTop, _getDocScrollLeft, Matrix2D, _setDoc, _getCTM } from "./utils/matrix.js";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1357:20)
    at Module._compile (node:internal/modules/cjs/loader:1414:41)
    at Module._extensions..js (node:internal/modules/cjs/loader:1534:10)
    at Module.load (node:internal/modules/cjs/loader:1265:32)
    at Module._load (node:internal/modules/cjs/loader:1081:12)
    at cjsLoader (node:internal/modules/esm/translators:344:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:284:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:235:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:461:24)
    at async nodeImport (file:///C:/Projekte/vault-of-ayes/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:52735:15)

09:36:22 [vite] Error when evaluating SSR module C:/Projekte/vault-of-ayes/modules/bismuth/src/routes/index.tsx: failed to import "gsap/Flip"
|- C:\Projekte\vault-of-ayes\node_modules\gsap\Flip.js:12
import { getGlobalMatrix, _getDocScrollTop, _getDocScrollLeft, Matrix2D, _setDoc, _getCTM } from "./utils/matrix.js";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1357:20)
    at Module._compile (node:internal/modules/cjs/loader:1414:41)
    at Module._extensions..js (node:internal/modules/cjs/loader:1534:10)
    at Module.load (node:internal/modules/cjs/loader:1265:32)
    at Module._load (node:internal/modules/cjs/loader:1081:12)
    at cjsLoader (node:internal/modules/esm/translators:344:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:284:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:235:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:461:24)
    at async nodeImport (file:///C:/Projekte/vault-of-ayes/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:52735:15)







09:36:22 [vite] Internal server error: Cannot use import statement outside a module
      at wrapSafe (node:internal/modules/cjs/loader:1357:20)
      at Module._compile (node:internal/modules/cjs/loader:1414:41)
      at Module._extensions..js (node:internal/modules/cjs/loader:1534:10)
      at Module.load (node:internal/modules/cjs/loader:1265:32)
      at Module._load (node:internal/modules/cjs/loader:1081:12)
      at cjsLoader (node:internal/modules/esm/translators:344:17)
      at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:284:7)
      at ModuleJob.run (node:internal/modules/esm/module_job:235:25)
      at async ModuleLoader.import (node:internal/modules/esm/loader:461:24)
      at async nodeImport (file:///C:/Projekte/vault-of-ayes/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:52735:15)
```

</details>

Removing the "registerPlugin" function fixes the issue but makes it basically unusable

**Comment by jackdoyle** [comment]
The first error sounds like you're trying to run GSAP in an environment where "document" and/or "window" are not defined. That can't work. In order to find selector text targets (which you're leveraging), GSAP needs access to document.querySelectorAll(). I'm completely unfamiliar with Qwik, but please make sure you're not running GSAP code in an SSR environment where document/window don't exist. Sometimes it's just a matter of wrapping your GSAP-related code in a conditional statement that checks to see if it's running server-side or cilent-side (only run it client-side). 

The Flip error sounds like a configuration problem on your end related to your codebase not understanding ES modules. You could try using the UMD files instead by importing from the "dist" folder, like "gsap/dist/Flip". 

If you're still having trouble, the best thing to do is create a minimal demo, like in Stackblitz, that clearly illustrates the problem with as little code as possible, and then post it here or in the forums at https://gsap.com/community.

**Comment by TheAyes** [comment]
The first error got indeed fixed by wrapping a function in a client context. I'm still rather new to fullstack environments so I must excuse myself for this. The second error however I was able to reproduce in a stackblitz right here:
https://stackblitz.com/edit/qwik-starter-1f37db?file=src%2Froutes%2Findex.tsx

**Comment by jackdoyle** [comment]
Yeah, that's probably because you're calling gsap.registerPlugin(Flip) in an area of your code that runs server-side (before document or window exist). So you can either wrap it in conditional code accordingly, or just tuck it inside your handler so that it only runs when it's on the client side (right above where your other GSAP-related code runs).

**Comment by TheAyes** [comment]
Well while it is indeed related to server/client sided code I see several inconsistencies in qwiks docs. Where they mention that "this code" runs on client yet I get the import error, but it resolves around an `if (isBrowser)` and at this point I'm just giving up trying.
It might just be my own inexperience but I'd expect things that should run only in the browser to only run in the browser.
Thanks for your valuable informations :)
